#!/bin/bash

echo "🚀 Minerva Receipt Processor - Deployment Helper"
echo "================================================"

echo ""
echo "✅ Frontend (Vercel) Deployment:"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import from GitHub: Rishi6277006/minerva-receipt-processor"
echo "4. Root Directory: . (root)"
echo "5. Framework: Next.js (auto-detected)"
echo "6. Click 'Deploy'"
echo ""

echo "✅ Backend (Railway) Deployment:"
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose: Rishi6277006/minerva-receipt-processor"
echo "5. Set Root Directory: packages/backend"
echo "6. Add environment variables (optional):"
echo "   - DATABASE_URL=your-postgresql-url"
echo "   - OPENAI_API_KEY=your-openai-key"
echo "7. Deploy!"
echo ""

echo "🔗 Connect Frontend to Backend:"
echo "1. After Railway deployment, copy the backend URL"
echo "2. In Vercel dashboard, add environment variable:"
echo "   NEXT_PUBLIC_BACKEND_URL=https://your-railway-backend-url.railway.app"
echo "3. Redeploy frontend"
echo ""

echo "📋 Current Status:"
echo "✅ Frontend builds successfully"
echo "✅ Backend builds successfully"
echo "✅ All build errors fixed"
echo "✅ .vercelignore configured"
echo "✅ Ready for deployment!"
echo ""

echo "🎯 Your application is ready to deploy!"
echo "Follow the steps above to get it live on Vercel and Railway." 